### ISSUE TITLE
Test watchers with geth 1.10.21 and redeploy

### ISSUE THREAD

**Issue by nikugogoi** [cerc-io/watcher-ts#160]
- [x] erc721-watcher
- [x] mobymask-watcher
  - [x] Add metrics config
- [x] uniswap-watcher
- [x] eden-watcher

**Comment by AFDudley** [comment]
Fir these deployments, We should be using the Blue Gre been style as @dboreham suggested. So we need to make staging environments that can be rotated into and out of production.

**Comment by AFDudley** [comment]
We may want to move this to an additional project board, i'm just not sure which one.
