### ISSUE TITLE
Document how to install yarn correctly on Linux

### ISSUE THREAD

**Issue by zramsay** [cerc-io/watcher-ts#275]
ie. https://stackoverflow.com/questions/53471063/yarn-error-there-are-no-scenarios-must-have-at-least-one
vs plain `apt install yarn` which will install but won't work with the stack

**Comment by ashwinphatak** [comment]
For local development, we install node itself using nvm (https://github.com/nvm-sh/nvm) and yarn using `npm install -g yarn`

**Comment by zramsay** [comment]
made ~ moot by SO.
