### ISSUE TITLE
Watcher docs updates & deduplication

### ISSUE THREAD

**Issue by zramsay** [cerc-io/watcher-ts#286]
Some watchers are now documented in 3 places: as a stack in SO, in their readme.md, and in their demo.md.
As well, across most watchers' readme/demo in this repo, there is a lot of duplication; eg. how to setup the stack, which is now somewhat redundant with SO.

My solution is to pull out all the duplicate information into a single document for devs to run the stack without SO. Then to merge any demo.md into the README.md, and where applicable point to the SO stack demo. The idea being that SO gets the ball rolling for folks then they come back here to get more into the weeds.

**Comment by AFDudley** [comment]
Sounds like a plan. Thanks.
