### ISSUE TITLE
Replace GitHub Actions builds with Jenkins Implementation

### ISSUE THREAD

**Issue by rickmanelius** [cerc-io/watcher-ts#304]

**Comment by rickmanelius** [comment]
Work has already been done. This is just to track/surface the work to ensure it's moving through the proper review/approval process.

**Comment by rickmanelius** [comment]
@lanceseidman Can you expose the instructions and information necessary to get this to a testable state?

**Comment by rickmanelius** [comment]
Looks like this is being tracked here https://github.com/cerc-io/watcher-ts/blob/bd4e2b3a88f450504f44d2abb742221ec513b710/Jenkinsfile2.

I'll step aside, but to the degree that Lance can assist Michael in getting this to a finish line, let's do that.

**Comment by zramsay** [comment]
closing as we're going to be using `act`
