### ISSUE TITLE
Relay / peer nodes stability issues

### ISSUE THREAD

**Issue by prathamesh0** [cerc-io/watcher-ts#323]
* We get the following error when a [relay node](https://github.com/cerc-io/watcher-ts/blob/v0.2.27/packages/peer/src/relay.ts) is kept running for some time:

  ```
  FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
  ```
  
  It appears to be a memory leak issue.
  
  On setting `--max-old-space-size=256`, we get error:
  
  ```
  # Fatal error in: ../../download/src/rtc_base/platform_thread.cc, line 87
  # last system error: 11
  # Check failed: 0 == pthread_create(&thread_, &attr, &StartThread, this) (0 vs. 11)
  # Aborted (core dumped)
  ```
* When left running for a long time (`~10` hours), a relay node uses upto 99% CPU
* Peers are sometimes unable to dial the relay nodes running on remote server (works on restarting the relay node)

**Comment by dboreham** [comment]
I found an old bug filed against the node-webrtc project that looks possibly related: https://github.com/node-webrtc/node-webrtc/issues/614

Certainly suspicious that our process died calling `pthread_create()`. A good first step would be to monitor the number of threads in the relay Node.js process.

**Comment by prathamesh0** [comment]
Issues encountered with test deployment on 20c infra:

- When running relay nodes, CPU usage goes on increasing with time
- Peers are sometimes unable to dial the relay nodes (works on restarting the relay node)
  - Seems to be happening in conjunction with the first issue
- `mobymask-v2-watcher` crashes with `Segmentation fault` if we run it with both relay and peer functionality enabled
